### ISSUE TITLE
[Taejun] todolist refactoring

### ISSUE THREAD

**Issue by Baek-Taejun** [innovation-camp-6/precTodoLists1#1]

**Comment by 19Edwin92** [comment]
01 src > components 폴더를 생성하고 
    - 컴포넌트를 분리하는 시도를 해보면 어떨까요?
    - App.js > TodoCard 컴포넌트의 파일분리시도

02 App.js 안에 중복되는 컴포넌트에 대한 부분에 대한 리펙토링
    - div className="working",  div className="done"
    - 하나의 컴포넌트로 만들고 props를 활용하여 재사용을 시도해보는 건 어떨까요?

**Comment by Baek-Taejun** [comment]
test 입니다.

**Comment by Baek-Taejun** [comment]
수정 했습니다. 확인부탁드립니다.

**Comment by 19Edwin92** [comment]
오 굳 ㅋㅋㅋ
